# Generated by Django 4.1.7 on 2024-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='end_time',
            new_name='Advance',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='start_time',
            new_name='Total',
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
