# Generated by Django 5.0.1 on 2024-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_end_time_bookings_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
