# Generated by Django 4.1.7 on 2024-02-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorprofile_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
    ]
